//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GeneDoc.rc
//
#define IDR_MAINFRAME                   2
#define IDR_GENEDOTYPE                  3
#define IDS_DUPSEQNAME                  4
#define IDR_SUMMARYVIEW                 5
#define IDR_TEXTVIEW                    6
#define IDR_DSTATVIEW                   7
#define IDR_PHYLOVIEW                   8
#define IDR_GELVIEW                     9
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_POS                101
#define IDD_PHYLOGEN                    103
#define IDD_SHADEEDITDLG                106
#define IDD_CONFDISPLAY                 108
#define IDD_CONFMODESTYLE               110
#define IDD_SEQDIALOG                   112
#define IDD_SEQDETAILS                  114
#define IDD_CONFSCORETABLES             119
#define IDD_CONFPRINT                   126
#define IDD_CONFPROPERTY                127
#define IDD_PROPEDITDLG                 128
#define IDD_TITLINGF                    132
#define IDD_COLORBAR                    134
#define IDB_PHYLOBAR                    142
#define IDB_GENEBAR                     143
#define IDB_GENEDOC                     144
#define IDB_SMALLLOGO                   145
#define IDD_SHOWTABLE                   146
#define IDB_DSTATBAR                    146
#define IDD_SCORECANDIALOG              147
#define IDD_GROUPPROP                   152
#define IDD_STRUCTUREPROP               153
#define IDD_DISPLAYGROUPNAME            154
#define IDD_GRAPHSETUP                  156
#define IDD_STCDATADET                  158
#define IDD_SEQUENCEINPUT               161
#define IDD_GROUPSELECT                 162
#define IDD_FINDREPLACE                 164
#define IDD_CHEMPROP                    165
#define IDD_IMPORTTYPE                  166
#define IDB_INLOVE                      167
#define IDD_SEARCH                      168
#define IDD_SRCHDLG                     169
#define IDD_PDBDIALOG                   170
#define IDD_HTMLPICK                    171
#define IDD_REFILT                      173
#define IDD_SRCHREP                     175
#define IDD_CONFIDENT                   176
#define IDD_EXPORTDLG                   177
#define IDD_LOGODDS                     178
#define IDD_LOGDLG                      179
#define IDD_SEQSEL                      181
#define IDD_MOTSEQ                      183
#define IDD_FIND                        184
#define IDD_SELARRSEQ                   186
#define IDD_SELPROJ                     187
#define IDD_DNATRANS                    188
#define IDD_GEL_FORM                    189
#define IDD_SEQALIGN                    190
#define IDD_GENBANK                     191
#define IDD_REPDLG                      192
#define IDB_BITMAP1                     193
#define IDB_BITMAP2                     194
#define IDC_TSIDE1                      1000
#define IDC_TSIDE2                      1001
#define IDC_SET2COUNT                   1002
#define IDC_PAGEWIDTH                   1003
#define IDC_PHYLOEDIT                   1004
#define IDC_PAGEHEIGHT                  1004
#define IDC_PHYLOEXPORT                 1005
#define IDC_CHGFONT                     1005
#define IDC_PHYLOIMPORT                 1006
#define IDC_SET1COUNT                   1006
#define IDC_FONTWEIGHT                  1007
#define IDC_XBORDERPCT                  1007
#define IDC_TSIDE3                      1008
#define IDC_CHANGEBACK80                1009
#define IDC_XAXISTITLEPCT               1009
#define IDC_CHANGEBACK100               1010
#define IDC_YBORDERPCT                  1010
#define IDC_CHANGEBACK60                1011
#define IDC_DSTATXPCT                   1011
#define IDC_CHANGEBACK0                 1012
#define IDC_DSTATYPCT                   1012
#define IDC_KSPRXPCT                    1013
#define IDC_80DISP                      1014
#define IDC_KSPRYPCT                    1014
#define IDC_CHANGEFORE80                1015
#define IDC_CHARTTITLE                  1015
#define IDC_100DISP                     1016
#define IDC_SHADELIST                   1016
#define IDC_YAXISTITLE                  1016
#define IDC_CHANGEFORE100               1017
#define IDC_SHADENEW                    1017
#define IDC_XAXISTITLE                  1017
#define IDC_60DISP                      1018
#define IDC_SHADEDELETE                 1018
#define IDC_YAXISTITLEPCT               1018
#define IDC_CHANGEFORE60                1019
#define IDC_SHADEEDIT                   1019
#define IDC_CHARTTITLEPCT               1019
#define IDC_0DISP                       1020
#define IDC_SHADEEDITNUM                1020
#define IDC_LINEWIDTH                   1020
#define IDC_CHANGEFORE0                 1021
#define IDC_SHADEEDITCONT               1021
#define IDC_XAXISROUNDING               1021
#define IDC_LEFTBORDER                  1023
#define IDC_RIGHTBORDER                 1024
#define IDC_TOPBORDER                   1025
#define IDC_BOTTOMBORDER                1026
#define IDC_EDITWIDTH                   1027
#define IDC_GENEFIXEDWIDTH              1028
#define IDC_GENEAUTOWIDTH               1029
#define IDC_STRSEC                      1031
#define IDC_STRPRIM                     1032
#define IDC_STRTERT                     1033
#define IDC_MODECONSERVED               1037
#define IDC_MODEQUANTIFY                1038
#define IDC_DIFFCONSENSUS               1040
#define IDC_DIFFTOPSEQ                  1041
#define IDC_PROPALL                     1043
#define IDC_LIST1                       1044
#define IDC_SEQMOVEUP                   1045
#define IDC_SEQMOVEDOWN                 1046
#define IDC_SEQDELETE                   1047
#define IDC_SEQIMPORT                   1048
#define IDC_SEQDETAILS                  1049
#define IDC_SEQDETNAME                  1050
#define IDC_CONSENSUSLINE               1051
#define IDC_CONSENSUSBELOW              1052
#define IDC_GENEGROUPENABLED            1053
#define IDC_CONSENSUSNONE               1053
#define IDC_SCORELIST                   1054
#define IDC_CURRENTSCORE                1055
#define IDC_SCORESETCURRENT             1056
#define IDC_SHADEDEFAULT                1058
#define IDC_SCOREDESCR                  1059
#define IDC_SEQDETWEIGHT                1060
#define IDC_SEQINDON                    1061
#define IDC_SEQINDOFF                   1062
#define IDC_ORPORT                      1063
#define IDC_ORLAND                      1064
#define IDC_GAPDASH                     1064
#define IDC_GAPDOT                      1065
#define IDC_PROPNEW                     1066
#define IDC_PROPDEL                     1067
#define IDC_PROPEDIT                    1068
#define IDC_PROPLEVEL1                  1069
#define IDC_PROPLEVEL2                  1070
#define IDC_PROPLEVEL3                  1071
#define IDC_PROPTEXTCOLOR               1072
#define IDC_PROPERTYLIST                1073
#define IDC_PROPEDITCONT                1074
#define IDC_PROPEDITNUM                 1075
#define IDC_PROPBKCOLOR                 1076
#define IDC_TYPEPROTEIN                 1078
#define IDC_TYPEMIXEDNUCLEIC            1083
#define IDC_TYPEDNA                     1084
#define IDC_MODEPROPERTY                1088
#define IDC_TYPERNA                     1089
#define IDC_TITLEPROGRAM                1095
#define IDC_TITLESCORE                  1096
#define IDC_TITLEOPENGAP                1097
#define IDC_TITLEEXTENDGAP              1098
#define IDC_TITLEEDIT                   1099
#define IDC_COLORLIST                   1106
#define IDC_PHYLOCOPY                   1111
#define IDC_PHYLOPASTE                  1112
#define IDC_SHOWTABLECOPY               1113
#define IDC_GROUPTEXTCOLOR              1113
#define IDC_MOVETOP                     1113
#define IDC_LEVELDEFAULTS               1113
#define IDC_STCLOADDATA                 1114
#define IDC_SCORETREE                   1115
#define IDC_SCOREPAIR                   1116
#define IDC_SCORETREENUMB               1117
#define IDC_PICTWIDTH                   1119
#define IDC_PICTHEIGHT                  1120
#define IDC_SHOWEDIT                    1120
#define IDC_PICTASCENT                  1121
#define IDC_SHOWSTATUS                  1121
#define IDC_COMBOMASTER                 1122
#define IDC_GROUPPCRLEVEL               1138
#define IDC_DATASETDET                  1140
#define IDC_EDITFONTPOINTS              1149
#define IDC_GROUPCONSLEVEL              1149
#define IDC_CHANGETEXT                  1157
#define IDC_CHANGEBACK                  1158
#define IDC_DISP                        1159
#define IDC_DataTypeList                1162
#define IDC_PROPCONSERVED               1163
#define IDC_RESDISPNORMAL               1165
#define IDC_RESDISPDIFF                 1166
#define IDC_MODESTRUCTURE               1167
#define IDC_SEQLIST                     1168
#define IDC_GROUPCOMBO                  1169
#define IDC_NEWGROUP                    1171
#define IDC_DELETEGROUP                 1172
#define IDC_GROUPNAME                   1173
#define IDC_GROUPBACKCOLOR              1174
#define IDC_GROUPCOLOR                  1175
#define IDC_SHADELEVEL0                 1176
#define IDC_SHADELEVEL2                 1177
#define IDC_SHADELEVEL3                 1178
#define IDC_SHADELEVEL4                 1179
#define IDC_MODIFYALL                   1180
#define IDC_SEQADD                      1181
#define IDC_REMOVESEQ                   1182
#define IDC_COLORSEQNAMES               1183
#define IDC_PRINTPAGE0                  1185
#define IDC_PRINTPAGE1                  1186
#define IDC_PRINTPAGE2                  1187
#define IDC_PRINTPAGE3                  1188
#define IDC_PRINTPAGE4                  1189
#define IDC_PRINTSTRINGFLAG1            1190
#define IDC_PRINTSTRINGFLAG2            1191
#define IDC_PRINTSTRINGFLAG0            1192
#define IDC_PRINTFONTNAME               1193
#define IDC_PRINTFONTPOINTS             1194
#define IDC_PRINTFONTWEIGHT             1195
#define IDC_PRINTPAGEOFFSET             1196
#define IDC_PRINTSTRING                 1197
#define IDC_CHANGEPRINTFONT             1198
#define IDC_GENEBLOCKPOS0               1199
#define IDC_GENEBLOCKPOS1               1200
#define IDC_GENEBLOCKPOS2               1201
#define IDC_MOVEBOTT                    1202
#define IDC_GROUPPCRSIM                 1203
#define IDC_DATADETLIST                 1204
#define IDC_SEQEXPORT                   1205
#define IDC_MARKERENABLED               1243
#define IDC_MARKERSYMBOL                1244
#define IDC_MARKERCOUNT                 1245
#define IDC_MARKERREPLACE               1246
#define IDC_MARKERSTART                 1247
#define IDC_CONSERVEDGAP                1248
#define IDC_COMPLIMENT                  1249
#define IDC_REVERSE                     1250
#define IDC_INPUT                       1251
#define IDC_SEQEDIT                     1252
#define IDC_SEQUENCENAME                1253
#define IDC_PASTE                       1254
#define IDC_RESIDUENORMAL               1255
#define IDC_RESIDUEUPPER                1256
#define IDC_RESIDUELOWER                1257
#define IDC_OTHERLIST                   1258
#define IDC_GROUPLIST                   1259
#define IDC_NAME1                       1259
#define IDC_NAME2                       1260
#define IDC_DUPLICATE                   1261
#define IDC_INSTRUCT                    1262
#define IDC_FINDSTRING                  1263
#define IDC_REPLACE                     1264
#define IDC_CHEMPROPFORE                1265
#define IDC_IMPORTTYPE0                 1301
#define IDC_IMPORTTYPE2                 1302
#define IDC_IMPORTTYPE3                 1303
#define IDC_IMPORTTYPE4                 1304
#define IDC_PROPCONSFORE                1305
#define IDC_IMPORTTYPE5                 1305
#define IDC_PROPCONSBACK                1309
#define IDC_CYSTEINE                    1317
#define IDC_REDUCED                     1318
#define IDC_CHEMPROP                    1319
#define IDC_PROPCONS                    1320
#define IDC_CHEMPROPBACK                1321
#define IDC_SHOWPROPERTY                1322
#define IDC_SHOWCONSERVE                1323
#define IDC_PHYSIOCHEM                  1324
#define IDC_NAMESEP                     1325
#define IDC_INDSEP                      1326
#define IDC_MAXNAME                     1327
#define IDC_EDIT                        1331
#define IDC_SEARCHLIST                  1332
#define IDC_DELETE                      1333
#define IDC_NEW                         1334
#define IDC_TEXTCOLOR                   1335
#define IDC_BACKCOLOR                   1336
#define IDC_PROSITE                     1337
#define IDC_REBASE                      1338
#define IDC_LOADFILE                    1343
#define IDC_WRITESCR                    1343
#define IDC_MOTIF                       1344
#define IDC_DECRIP                      1345
#define IDC_NAME                        1346
#define IDC_LOADREBASE                  1347
#define IDC_MOVEUP                      1348
#define IDC_MOVEDOWN                    1349
#define IDC_CLEARALL                    1351
#define IDC_SAFEMODE                    1352
#define IDC_PDBOFFSET                   1353
#define IDC_INCLUDEBASE                 1354
#define IDC_FULLTABLE                   1356
#define IDC_TEXTONLY                    1358
#define IDC_FULLWEB                     1359
#define IDC_HTMLONLY                    1360
#define IDC_MODESEARCH                  1361
#define IDC_DISPSIDE                    1363
#define IDC_SIDEDISP                    1364
#define IDC_SIDECOLORLIST               1367
#define IDC_COMBOBACK                   1368
#define IDC_CONSSUBIDENT                1369
#define IDC_CONSSUBDEMOTE               1370
#define IDC_CONSSUBTERT                 1371
#define IDC_DNAAMBEN                    1373
#define IDC_DNAAMBDIS                   1374
#define IDC_MINLEN                      1375
#define IDC_MAXLEN                      1376
#define IDC_EXCLUDE                     1377
#define IDC_INCLUDE                     1378
#define IDC_NONAMBIG                    1380
#define IDC_PALIN                       1381
#define IDC_OCCUR                       1383
#define IDC_PROPENAB                    1384
#define IDC_WRITERE                     1385
#define IDC_OVERLAP                     1386
#define IDC_PRINTSHADE                  1387
#define IDC_EXCLDUP                     1389
#define IDC_CUTSITES                    1408
#define IDC_SORTEDFRAG                  1409
#define IDC_UNIQUEFRAG                  1410
#define IDC_UNIQFRAGPER                 1411
#define IDC_GROUPFRAG                   1412
#define IDC_SIMPER                      1413
#define IDC_SORTEDCUT                   1414
#define IDC_UNIQPER                     1415
#define IDC_SIMILARITY                  1417
#define IDC_LISTSEQUENCE                1418
#define IDC_DESCRIPTION                 1421
#define IDC_ALL                         1424
#define IDC_BACKBONE                    1425
#define IDC_SIDEONLY                    1426
#define IDC_TEXTSTART                   1427
#define IDC_SHOWALL                     1428
#define IDC_SHOWLEVEL                   1429
#define IDC_TOGGLE                      1430
#define IDC_SUMCOLINCH                  1432
#define IDC_SUMCOLINCHDIS               1433
#define IDC_COL2WID11                   1434
#define IDC_SUM2COL02                   1435
#define IDC_SUMDEFDIS                   1436
#define IDC_SUMTEXTBLACK                1437
#define IDC_FILE                        1438
#define IDC_CLIP                        1439
#define IDC_IMPORTTYPE6                 1440
#define IDIMPORT                        1441
#define IDEXPORT                        1442
#define IDC_TEXTNOGAP                   1444
#define IDC_EXPORTTYPE                  1445
#define IDC_SELALLSEQ                   1446
#define IDC_SELLISTSEQ                  1447
#define IDC_ENABLED                     1450
#define IDC_MEME                        1451
#define IDC_MOTIFLIST                   1452
#define IDC_BAYES                       1453
#define IDC_MODE                        1454
#define IDC_MODE2                       1455
#define IDC_MODE4                       1456
#define IDC_ALLOWOV                     1457
#define IDC_MODE3                       1458
#define IDC_BETTERTHAN                  1459
#define IDC_BESTN                       1460
#define IDC_TRILEVEL2                   1461
#define IDC_TRILEVEL3                   1462
#define IDC_TRILEVEL1                   1463
#define IDC_LOGODDS                     1464
#define IDC_OUTTAB                      1467
#define IDC_MPC                         1468
#define IDC_BACKGROUND                  1470
#define IDC_BACKGROUND2                 1471
#define IDC_LISTMOTIF                   1473
#define IDC_RGBBACK                     1474
#define IDC_RGBTEXT                     1475
#define IDC_STATICT                     1476
#define IDC_DESCR                       1476
#define IDC_FINDSTR                     1476
#define IDC_STATICG                     1477
#define IDC_MISMATCH                    1477
#define IDC_STATICC                     1478
#define IDC_INSDEL                      1478
#define IDC_STATICA                     1479
#define IDC_SEQCOUNT                    1480
#define IDC_EXCLUDEO                    1481
#define IDC_IMPORTTYPE7                 1482
#define IDC_EXNT                        1483
#define IDC_IUPAC                       1484
#define IDC_PRINTDATE                   1485
#define IDC_PRINTFILENAME               1486
#define IDC_LISTSEQUENCES               1487
#define IDC_FINDSTART                   1488
#define IDC_FINDBEFORE                  1489
#define IDC_FINDFROM                    1490
#define IDC_FINDALL                     1491
#define IDC_TRANSTIDLE                  1492
#define IDC_GENEALIGNWIDTH              1493
#define IDC_SHOWMANSHADE                1494
#define IDC_SHOWCOMMENTS                1495
#define IDC_SCORELOG                    1496
#define IDC_PROJLIST                    1497
#define IDC_DESEL                       1498
#define IDC_COMPLEMENT                  1499
#define IDC_COMBCODON                   1500
#define IDC_LISTCODON                   1502
#define IDC_TRANSCOLUMNS                1504
#define IDC_SHIFT0                      1505
#define IDC_SHIFT1                      1506
#define IDC_SHIFT2                      1507
#define IDC_TRANSFIXED                  1510
#define IDC_TRANSFLOAT                  1511
#define IDC_TRANSFIXEDSTART             1512
#define IDC_ALTSTART                    1513
#define IDC_ALTPROT                     1514
#define IDC_ALTCODON                    1515
#define IDC_TRANSFLTSTART               1516
#define IDC_LISTENZYME                  1522
#define IDC_RUNGEL                      1523
#define IDC_EDITCOPY                    1524
#define IDC_ALIGNMETH1                  1526
#define IDC_ALIGNMETH0                  1527
#define IDC_GAPLEN                      1530
#define IDC_GAPOPEN                     1531
#define IDC_GAPEXTEND                   1532
#define IDC_SORTDESC                    1533
#define IDC_SCORETABLE                  1534
#define IDC_GENBANK                     1535
#define IDC_LOCUS                       1536
#define IDC_ACCESSION                   1537
#define IDC_NID                         1538
#define IDC_TRANSLATION                 1539
#define IDC_ORIGIN                      1540
#define IDC_ALIGNEDGAPS                 1541
#define IDC_JUXTAPOSITION               1542
#define IDC_EXACTMATCH                  1543
#define IDC_OUTMATRIX                   1544
#define IDC_OUTROWS                     1545
#define IDC_ABSOLUTEVAL                 1546
#define IDC_PERCENTVAL                  1547
#define IDC_LABELSINGLE                 1548
#define IDC_LABELTWO                    1549
#define IDC_LABELTOP                    1550
#define IDC_LABELTOPLEFT                1551
#define IDC_INC_AA                      1553
#define IDC_GROUPSEL                    1554
#define IDC_MAKEBACKUPS                 1555
#define IDC_SORTNAME                    1556
#define IDC_SAVESORT                    1557
#define IDC_LOADSORT                    1558
#define IDC_LOCAFTERSEQ                 1559
#define IDC_LOCAFTERNAME                1560
#define IDC_DEGAP                       1561
#define IDC_COUNTSEL                    1562
#define IDC_PID                         1564
#define ID_EDIT_COPYINV                 32779
#define IDM_CONFIGURE                   32780
#define IDM_GENEARRANGE                 32782
#define IDM_SELECT                      32787
#define IDM_GENEAUTOSHADE4              32790
#define IDM_GENEAUTOSHADE3              32791
#define IDM_GENEAUTOSHADE2              32792
#define IDM_GENEINSERTDASH              32794
#define IDM_GENEDELETEDASH              32795
#define IDM_GENECLEARSHADE              32796
#define IDM_SELECTCOL                   32801
#define IDM_GENECREATEWIN               32802
#define IDM_GENEMODEQUANTIFY            32805
#define IDM_GENEEDITSEQ                 32806
#define IDM_GENEMODECONSERVED           32807
#define IDM_GENESCORE                   32808
#define IDM_GENEINSERTOTHER             32809
#define IDM_GENEDELETEOTHER             32810
#define IDM_GENEDELETEFILL              32814
#define IDM_GENEINSERTFILL              32815
#define IDM_GENEGROUPENABLE             32816
#define ID_ON_HELP                      32817
#define IDM_GENESTATFILE                32820
#define IDM_GENESCOREFILE               32821
#define IDM_GENESAVEINI                 32822
#define IDM_GENELOADINI                 32823
#define IDM_GENEMODEPROPERTY            32826
#define IDM_TITLINGF                    32827
#define IDM_MANUALSHADE                 32828
#define ID_EDIT_COPY8                   32829
#define ID_EDIT_COPY0                   32830
#define ID_EDIT_COPYINV0                32832
#define ID_PHYLOBAR                     32833
#define ID_EDIT_COPYINV8                32834
#define ID_EDIT_COPYBIT                 32835
#define ID_EDIT_COPYINVBIT              32836
#define IDM_PHYLODLG                    32837
#define IDM_PHYLOVIEW                   32838
#define IDM_PHYLODELETE                 32840
#define IDM_PHYLOCLEAR                  32841
#define IDM_GENEVIEW                    32842
#define IDM_GENESCOREPAIR               32843
#define IDM_GENESCORETREE               32844
#define IDM_GENECLEARSCORE              32845
#define IDM_PHYLOCREATE                 32846
#define IDM_PHYLOMVUP                   32847
#define IDM_PHYLOMVDN                   32848
#define IDM_PHYLOCOPY                   32849
#define IDM_COPYTEXT                    32851
#define IDM_GENECOPYPICT                32852
#define IDM_GENEEDITMODE                32853
#define IDM_SHOWTABLE                   32854
#define IDM_GENESCORENUMB               32855
#define IDM_GENESCOREINFO               32857
#define IDM_GENEMODESTRUCTURE           32863
#define IDM_GENERESIDUEMODEDIFF         32865
#define IDM_EDITGROUPPROP               32866
#define IDM_GENESHADEGROUPS             32867
#define IDM_GENESHADEGROUPCONSERVE      32869
#define IDM_GENESHADECONTRAST           32870
#define IDM_GENESHADECONTRASTNOGAP      32871
#define IDM_COPYMETACLIP                32872
#define IDM_COPYMETAFILE                32873
#define IDM_STCLOADPSDB                 32876
#define IDM_STCLOADUSERFILE             32878
#define IDM_STCLEARALL                  32880
#define IDM_STCLOADEMBL                 32881
#define IDM_GENEDSTATVIEW               32883
#define IDM_DSTATCOPY                   32884
#define IDM_DSTATSCORE                  32885
#define IDM_DSTATGRAPHSETUP             32887
#define IDM_DSTATWRITEDATA              32888
#define IDM_DSTATREADSET1               32889
#define IDM_DSTATREADSET2               32890
#define IDM_DSTATREADSETS               32891
#define IDM_DSTATWRITESCORE             32893
#define IDM_DSTATSCOREALL               32894
#define IDM_GROUPSHADEPCR               32895
#define IDM_GROUPSHADEPCRSIM            32896
#define IDM_FILEEXPORT                  32897
#define IDM_FILEIMPORT                  32898
#define IDM_CLEARGAPCOLS                32899
#define IDM_PLOTSTATDSTAT               32900
#define IDM_PLOTFAVSUBS                 32901
#define IDM_PLOTGROUP                   32902
#define IDM_PLOTGROUPFAV                32903
#define IDM_GENEFINDREPLACE             32904
#define IDM_GENECOPYSEQ                 32905
#define IDM_GENESHADEGROUPPHYSCHEM      32914
#define IDM_GENEMODEPHYSIOCHEM          32915
#define IDM_GENEGROUPSGCONX             32916
#define IDM_GENEMODESEARCH              32917
#define IDM_GENECOPYHTML                32919
#define IDM_DISPTREEWEIGHT              32920
#define IDM_GENESCOREKEY                32921
#define IDM_GENESHADEGROUPDNA           32922
#define IDM_SRCHREPVIEW                 32923
#define IDM_PLOTFRAG                    32924
#define IDM_GENEMODESIMILARITY          32925
#define IDM_STCLOADPDB                  32926
#define IDM_SUMMARYVIEW                 32927
#define IDM_GENECOPYRTF                 32928
#define IDM_GENEMODELOGODDS             32929
#define IDM_GENEWRITELOGODDS            32930
#define IDM_LOGODDSVIEW                 32931
#define IDM_GENEMOVE                    32932
#define IDM_DELCOLUMNS                  32933
#define IDM_FIND                        32935
#define IDM_FINDNEXT                    32936
#define IDM_COPYCONS                    32938
#define IDM_SHOWMANSHADE                32939
#define IDM_SHOWCOMMENTS                32940
#define IDM_CLEARMANSHADE               32941
#define IDM_CLEARCOMMENTS               32942
#define IDM_SELECTARRSEQ                32943
#define IDM_GENESCORELO                 32945
#define ID_SCORING_RESCOREALLSCORES     32946
#define IDM_RESCOREALL                  32947
#define IDM_COMPLIMENTSEL               32952
#define IDM_REPLACEFROMPROJ             32954
#define IDM_GENEINSERTONE               32957
#define IDM_DNATRANS                    32958
#define IDM_GENEDELETEONE               32959
#define IDM_GENEREPORTVIEW              32960
#define IDM_DNAFFREQREP                 32961
#define IDM_REPSAVEFILE                 32962
#define IDM_REGAPDNA                    32964
#define IDM_GENEGELVIEW                 32965
#define IDM_DNACOLFREQREP               32966
#define IDM_DNACOLFRWREP                32967
#define IDM_ALIGN                       32968
#define IDM_MANSHADEREP                 32969
#define IDM_SHADING_REP                 32970
#define IDM_CONFIGREPORT                32972
#define IDM_CONSPROSITE                 32973
#define IDS_SEQDELSEQ                   57645
#define IDS_NOMOREPAGES                 57646
#define IDS_DISPLAYMAX                  57647
#define IDS_NEWFAILED                   57654
#define IDS_EXCEPTION                   57655

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32974
#define _APS_NEXT_CONTROL_VALUE         1567
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
